name: Update Homebrew Formula

on:
  workflow_call:
    inputs:
      tag:
        description: Tag to publish in the Homebrew tap
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish in the Homebrew tap, for example v0.4.0
        required: true
        type: string

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Homebrew Formula
        run: ./.github/scripts/update-homebrew-formula.sh "${{ inputs.tag }}"
        env:
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
